POST http://localhost:3002/calc
content-type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
  "target": 2.5
}

###
POST http://localhost:3002/calc
content-type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
  "target": "meow"
}

###
POST http://localhost:3002/calc
content-type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5]
}

###
POST http://localhost:3000/api/diaries
content-type: application/json

{
  "date": "2022-05-11",
  "weather": "cloudy",
  "visibility": "good",
  "comment": "new flight"
}

###
POST http://localhost:3001/api/patients
content-type: application/json

{
"dateOfBirth": "123",
"gender": "male",
"name": "John Doe",
"occupation": "Analog evangelist",
"ssn": "123-332"
}