POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Lars Monson",
  "username": "Monson",
  "password": "adv"
}
###
GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Users React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/"
  }